spring:
  cloud:
    gateway:
      routes:
        - id: ware_routes
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}


        - id: member_routes
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: thirdport-oss
          uri: lb://thirdport
          predicates:
            - Path=/api/thirdport/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: product_routes
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}


        - id: renren-fast
          uri: lb://renren-fast
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
